#!/usr/bin/env python
# 2013 Kyle Fitzsimmons
'''Class of lookup tables derived from the supplementary .dbf tables for the Assessment Roll 2011 shapefile'''

class LookupTable:
    dom_b72lien_tab = {
        'B': "",
        'C': " l'",
        'D': " la",
        'E': "au",
        'F': "aux",
        'G': "chez",
        'H': "d'",
        'I': "de",
        'J': "de l'",
        'K': "de la",
        'L': "des",
        'M': "du",
        'N': "l'",
        'O': "la",
        'P': "le",
        "Q": "les"
    }

    dom_b72r1_tab = {
        '01' : ['aucun'],
        '02' : ['all\xc3\xa9e', 'allee'],
        '05' : ['autoroute'],
        '08' : ['avenue', 'av.'],
        '11' : ['boulevard', 'boul.'],
        '14' : ['carr\xc3\xa9', 'carre'],
        '15' : ['carrefour'],
        '16' : ['chauss\xc3\xa9e', 'chaussee'],
        '17' : ['chemin', 'ch.'],
        '20' : ['cercle'],
        '21' : ['circuit'],
        '22' : ['concession'],
        '23' : ['c\xc3\xb4te', 'cote'],
        '25' : ['cours'],
        '26' : ['court'],
        '29' : ['crescent'],
        '32' : ['croissant', 'crois.'],
        '34' : ['descente'],
        '35' : ['desserte'],
        '36' : ['domaine'],
        '38' : ['drive'],
        '39' : ['\xc3\xa9changeur', 'echangeur'],
        '40' : ['esplanade'],
        '41' : ['fief'],
        '44' : ['garden'],
        '45' : ['gardens'],
        '46' : ['hill'],
        '47' : ['\xc3\xaele', 'ile'],
        '50' : ['impasse', 'imp.'],
        '52' : ['jardin'],
        '53' : ['lane'],
        '54' : ['lac'],
        '55' : ['ligne'],
        '56' : ['mont\xc3\xa9e', 'montee'],
        '57' : ['park'],
        '58' : ['passerelle'],
        '59' : ['parc'],
        '60' : ['piste'],
        '61' : ['passage'],
        '62' : ['place'],
        '63' : ['plage'],
        '64' : ['plaza'],
        '65' : ['pont'],
        '66' : ['plateau'],
        '67' : ['portage'],
        '68' : ['rampe'],
        '69' : ['promenade'],
        '70' : ['quai'],
        '71' : ['rang'],
        '72' : ['ridge'],
        '73' : ['petit rang'],
        '74' : ['road'],
        '75' : ['rond-point'],
        '76' : ['grand rang'],
        '77' : ['route'],
        '78' : ['route rurale'],
        '80' : ['rue'],
        '83' : ['ruelle'],
        '85' : ['sentier'],
        '86' : ['square'],
        '87' : ['street'],
        '89' : ['terrasse', 'tsse.'],
        '91' : ['traverse'],
        '92' : ['trait carr\xc3\xa9', 'trait carre'],
        '93' : ['tunnel'],
        '94' : ['viaduc'],
        '95' : ['voie']
    }
